### ISSUE TITLE
Broken on premise :(

### ISSUE THREAD

**Issue by aneillans** [DarqueWarrior/team#11]
Unfortunately #10 breaks on premise usage of the module.  Need to consider a different way for identifying whether the user has entered a FQDN (i.e. local) TFS server, or means a VSTS account.
Ironically, possibly the best method would be just looking for a slash (/) as this wouldn't be in an account name, but would be guaranteed to be present in an on-premise url. 

Thoughts?

**Comment by aneillans** [comment]
"Fix" for it in #12   I'm not happy with the fix, its hacky, but it works. Needs more thought I think.

**Comment by DarqueWarrior** [comment]
Do you still have concerns about this fix?

**Comment by aneillans** [comment]
Yeah, but it generally works. It definitely has a smell about it.

**Comment by DarqueWarrior** [comment]
Feel free to submit a PR for a better fix. I have not had any issues so I am going to close this. Thanks.
