### ISSUE TITLE
Whats does mean "Removed default project" after run "Add-TeamAccount"?

### ISSUE THREAD

**Issue by adailsonfilho** [DarqueWarrior/team#23]
Hi there,

First of all, thank you for making this open source!

After run `Add-TeamAccount` command and fill the fields we get this message: `Removed default project`. It is not clear for me what happened, maybe the same happens to other users.

There follows the snippet:

`PS C:\devops\tests\test01> Add-TeamAccount
cmdlet Add-TeamAccount at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
Account: suati\adailson.queiroz
SecurePersonalAccessToken: ****************************************************
Removed default project`

**Comment by DarqueWarrior** [comment]
I need to make that more clear. You can use the Set-DefaultProject function so you don't have to pass the -ProjectName parameter with every call. When you add a new account the default project gets cleared. That is just a message letting you know if you had one set you need to reset it.

**Comment by DarqueWarrior** [comment]
It a actually explained if you run help Add-TeamAccount.

![image](https://user-images.githubusercontent.com/3853405/30753332-a52fd6ce-9f84-11e7-9ad7-cabbe3644401.png)

Any suggestions on making this more clear?
