### ISSUE TITLE
Add-Build should accept build definition id

### ISSUE THREAD

**Issue by rsaa** [DarqueWarrior/team#9]
VSTS build system allows creating multiple build definitions with same name in different folders. We would like to take advantage of this feature because we have different branches of same software at different clients. So, we would like to create build folders by branch name and copy paste the build definitions and just change the source branch. Add-Build cmdlet doesn't support this. It takes BuildDefnition as string and tries to find a unique build definition by passed-in name and raises error when it finds more than one build definition with same name. I think it should have the option to accept id and name or even BuildDefinition object so caller can resolve before calling Add-Build and pass whatever makes sense. Any thoughts?

**Comment by DarqueWarrior** [comment]
Sorry for delay. I will work on this.

**Comment by DarqueWarrior** [comment]
I am working on this now.  I did two things:

1. You can now queue by build id
2. When you tab through build def names they are fully qualified with the path.

**Comment by DarqueWarrior** [comment]
Fixed in latest version.

**Comment by rsaa** [comment]
I will look into it soon. Thank you very much.
